/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Campaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Campaign{}

// Campaign struct for Campaign
type Campaign struct {
	CreatedAt string `json:"created_at"`
	CreatedBy User `json:"created_by"`
	DeadlineAt *string `json:"deadline_at,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	Vulnerabilities VulnerabilityCount `json:"vulnerabilities"`
	VulnerabilitiesBurndown TimeSeries `json:"vulnerabilities_burndown"`
}

type _Campaign Campaign

// NewCampaign instantiates a new Campaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaign(createdAt string, createdBy User, id string, name string, status string, updatedAt string, vulnerabilities VulnerabilityCount, vulnerabilitiesBurndown TimeSeries) *Campaign {
	this := Campaign{}
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.Id = id
	this.Name = name
	this.Status = status
	this.UpdatedAt = updatedAt
	this.Vulnerabilities = vulnerabilities
	this.VulnerabilitiesBurndown = vulnerabilitiesBurndown
	return &this
}

// NewCampaignWithDefaults instantiates a new Campaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignWithDefaults() *Campaign {
	this := Campaign{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *Campaign) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Campaign) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *Campaign) GetCreatedBy() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedByOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *Campaign) SetCreatedBy(v User) {
	o.CreatedBy = v
}

// GetDeadlineAt returns the DeadlineAt field value if set, zero value otherwise.
func (o *Campaign) GetDeadlineAt() string {
	if o == nil || IsNil(o.DeadlineAt) {
		var ret string
		return ret
	}
	return *o.DeadlineAt
}

// GetDeadlineAtOk returns a tuple with the DeadlineAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetDeadlineAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeadlineAt) {
		return nil, false
	}
	return o.DeadlineAt, true
}

// HasDeadlineAt returns a boolean if a field has been set.
func (o *Campaign) HasDeadlineAt() bool {
	if o != nil && !IsNil(o.DeadlineAt) {
		return true
	}

	return false
}

// SetDeadlineAt gets a reference to the given string and assigns it to the DeadlineAt field.
func (o *Campaign) SetDeadlineAt(v string) {
	o.DeadlineAt = &v
}

// GetId returns the Id field value
func (o *Campaign) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Campaign) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Campaign) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Campaign) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *Campaign) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Campaign) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Campaign) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Campaign) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetVulnerabilities returns the Vulnerabilities field value
func (o *Campaign) GetVulnerabilities() VulnerabilityCount {
	if o == nil {
		var ret VulnerabilityCount
		return ret
	}

	return o.Vulnerabilities
}

// GetVulnerabilitiesOk returns a tuple with the Vulnerabilities field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetVulnerabilitiesOk() (*VulnerabilityCount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vulnerabilities, true
}

// SetVulnerabilities sets field value
func (o *Campaign) SetVulnerabilities(v VulnerabilityCount) {
	o.Vulnerabilities = v
}

// GetVulnerabilitiesBurndown returns the VulnerabilitiesBurndown field value
func (o *Campaign) GetVulnerabilitiesBurndown() TimeSeries {
	if o == nil {
		var ret TimeSeries
		return ret
	}

	return o.VulnerabilitiesBurndown
}

// GetVulnerabilitiesBurndownOk returns a tuple with the VulnerabilitiesBurndown field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetVulnerabilitiesBurndownOk() (*TimeSeries, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VulnerabilitiesBurndown, true
}

// SetVulnerabilitiesBurndown sets field value
func (o *Campaign) SetVulnerabilitiesBurndown(v TimeSeries) {
	o.VulnerabilitiesBurndown = v
}

func (o Campaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Campaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["created_by"] = o.CreatedBy
	if !IsNil(o.DeadlineAt) {
		toSerialize["deadline_at"] = o.DeadlineAt
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["vulnerabilities"] = o.Vulnerabilities
	toSerialize["vulnerabilities_burndown"] = o.VulnerabilitiesBurndown
	return toSerialize, nil
}

func (o *Campaign) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"created_by",
		"id",
		"name",
		"status",
		"updated_at",
		"vulnerabilities",
		"vulnerabilities_burndown",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaign := _Campaign{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaign)

	if err != nil {
		return err
	}

	*o = Campaign(varCampaign)

	return err
}

type NullableCampaign struct {
	value *Campaign
	isSet bool
}

func (v NullableCampaign) Get() *Campaign {
	return v.value
}

func (v *NullableCampaign) Set(val *Campaign) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaign(val *Campaign) *NullableCampaign {
	return &NullableCampaign{value: val, isSet: true}
}

func (v NullableCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


