/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the API type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &API{}

// API struct for API
type API struct {
	AppCount int32 `json:"app_count"`
	CreatedAt string `json:"created_at"`
	EndpointCount int32 `json:"endpoint_count"`
	Host Host `json:"host"`
	Id string `json:"id"`
	IsFirstParty bool `json:"is_first_party"`
	TrafficVolume TimeSeries `json:"traffic_volume"`
	Vulnerabilities *VulnerabilityCount `json:"vulnerabilities,omitempty"`
}

type _API API

// NewAPI instantiates a new API object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPI(appCount int32, createdAt string, endpointCount int32, host Host, id string, isFirstParty bool, trafficVolume TimeSeries) *API {
	this := API{}
	this.AppCount = appCount
	this.CreatedAt = createdAt
	this.EndpointCount = endpointCount
	this.Host = host
	this.Id = id
	this.IsFirstParty = isFirstParty
	this.TrafficVolume = trafficVolume
	return &this
}

// NewAPIWithDefaults instantiates a new API object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIWithDefaults() *API {
	this := API{}
	return &this
}

// GetAppCount returns the AppCount field value
func (o *API) GetAppCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AppCount
}

// GetAppCountOk returns a tuple with the AppCount field value
// and a boolean to check if the value has been set.
func (o *API) GetAppCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppCount, true
}

// SetAppCount sets field value
func (o *API) SetAppCount(v int32) {
	o.AppCount = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *API) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *API) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *API) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetEndpointCount returns the EndpointCount field value
func (o *API) GetEndpointCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndpointCount
}

// GetEndpointCountOk returns a tuple with the EndpointCount field value
// and a boolean to check if the value has been set.
func (o *API) GetEndpointCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointCount, true
}

// SetEndpointCount sets field value
func (o *API) SetEndpointCount(v int32) {
	o.EndpointCount = v
}

// GetHost returns the Host field value
func (o *API) GetHost() Host {
	if o == nil {
		var ret Host
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *API) GetHostOk() (*Host, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *API) SetHost(v Host) {
	o.Host = v
}

// GetId returns the Id field value
func (o *API) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *API) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *API) SetId(v string) {
	o.Id = v
}

// GetIsFirstParty returns the IsFirstParty field value
func (o *API) GetIsFirstParty() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsFirstParty
}

// GetIsFirstPartyOk returns a tuple with the IsFirstParty field value
// and a boolean to check if the value has been set.
func (o *API) GetIsFirstPartyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsFirstParty, true
}

// SetIsFirstParty sets field value
func (o *API) SetIsFirstParty(v bool) {
	o.IsFirstParty = v
}

// GetTrafficVolume returns the TrafficVolume field value
func (o *API) GetTrafficVolume() TimeSeries {
	if o == nil {
		var ret TimeSeries
		return ret
	}

	return o.TrafficVolume
}

// GetTrafficVolumeOk returns a tuple with the TrafficVolume field value
// and a boolean to check if the value has been set.
func (o *API) GetTrafficVolumeOk() (*TimeSeries, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrafficVolume, true
}

// SetTrafficVolume sets field value
func (o *API) SetTrafficVolume(v TimeSeries) {
	o.TrafficVolume = v
}

// GetVulnerabilities returns the Vulnerabilities field value if set, zero value otherwise.
func (o *API) GetVulnerabilities() VulnerabilityCount {
	if o == nil || IsNil(o.Vulnerabilities) {
		var ret VulnerabilityCount
		return ret
	}
	return *o.Vulnerabilities
}

// GetVulnerabilitiesOk returns a tuple with the Vulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *API) GetVulnerabilitiesOk() (*VulnerabilityCount, bool) {
	if o == nil || IsNil(o.Vulnerabilities) {
		return nil, false
	}
	return o.Vulnerabilities, true
}

// HasVulnerabilities returns a boolean if a field has been set.
func (o *API) HasVulnerabilities() bool {
	if o != nil && !IsNil(o.Vulnerabilities) {
		return true
	}

	return false
}

// SetVulnerabilities gets a reference to the given VulnerabilityCount and assigns it to the Vulnerabilities field.
func (o *API) SetVulnerabilities(v VulnerabilityCount) {
	o.Vulnerabilities = &v
}

func (o API) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o API) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_count"] = o.AppCount
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["endpoint_count"] = o.EndpointCount
	toSerialize["host"] = o.Host
	toSerialize["id"] = o.Id
	toSerialize["is_first_party"] = o.IsFirstParty
	toSerialize["traffic_volume"] = o.TrafficVolume
	if !IsNil(o.Vulnerabilities) {
		toSerialize["vulnerabilities"] = o.Vulnerabilities
	}
	return toSerialize, nil
}

func (o *API) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_count",
		"created_at",
		"endpoint_count",
		"host",
		"id",
		"is_first_party",
		"traffic_volume",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPI := _API{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPI)

	if err != nil {
		return err
	}

	*o = API(varAPI)

	return err
}

type NullableAPI struct {
	value *API
	isSet bool
}

func (v NullableAPI) Get() *API {
	return v.value
}

func (v *NullableAPI) Set(val *API) {
	v.value = val
	v.isSet = true
}

func (v NullableAPI) IsSet() bool {
	return v.isSet
}

func (v *NullableAPI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPI(val *API) *NullableAPI {
	return &NullableAPI{value: val, isSet: true}
}

func (v NullableAPI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


