/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccessDeniedError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessDeniedError{}

// AccessDeniedError struct for AccessDeniedError
type AccessDeniedError struct {
	Error string `json:"error"`
}

type _AccessDeniedError AccessDeniedError

// NewAccessDeniedError instantiates a new AccessDeniedError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessDeniedError(error_ string) *AccessDeniedError {
	this := AccessDeniedError{}
	this.Error = error_
	return &this
}

// NewAccessDeniedErrorWithDefaults instantiates a new AccessDeniedError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessDeniedErrorWithDefaults() *AccessDeniedError {
	this := AccessDeniedError{}
	return &this
}

// GetError returns the Error field value
func (o *AccessDeniedError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *AccessDeniedError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *AccessDeniedError) SetError(v string) {
	o.Error = v
}

func (o AccessDeniedError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessDeniedError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *AccessDeniedError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessDeniedError := _AccessDeniedError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccessDeniedError)

	if err != nil {
		return err
	}

	*o = AccessDeniedError(varAccessDeniedError)

	return err
}

type NullableAccessDeniedError struct {
	value *AccessDeniedError
	isSet bool
}

func (v NullableAccessDeniedError) Get() *AccessDeniedError {
	return v.value
}

func (v *NullableAccessDeniedError) Set(val *AccessDeniedError) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessDeniedError) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessDeniedError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessDeniedError(val *AccessDeniedError) *NullableAccessDeniedError {
	return &NullableAccessDeniedError{value: val, isSet: true}
}

func (v NullableAccessDeniedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessDeniedError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


