/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssetCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetCount{}

// AssetCount struct for AssetCount
type AssetCount struct {
	FirstParty int32 `json:"first_party"`
	ThirdParty int32 `json:"third_party"`
	Total int32 `json:"total"`
}

type _AssetCount AssetCount

// NewAssetCount instantiates a new AssetCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetCount(firstParty int32, thirdParty int32, total int32) *AssetCount {
	this := AssetCount{}
	this.FirstParty = firstParty
	this.ThirdParty = thirdParty
	this.Total = total
	return &this
}

// NewAssetCountWithDefaults instantiates a new AssetCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetCountWithDefaults() *AssetCount {
	this := AssetCount{}
	return &this
}

// GetFirstParty returns the FirstParty field value
func (o *AssetCount) GetFirstParty() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FirstParty
}

// GetFirstPartyOk returns a tuple with the FirstParty field value
// and a boolean to check if the value has been set.
func (o *AssetCount) GetFirstPartyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstParty, true
}

// SetFirstParty sets field value
func (o *AssetCount) SetFirstParty(v int32) {
	o.FirstParty = v
}

// GetThirdParty returns the ThirdParty field value
func (o *AssetCount) GetThirdParty() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ThirdParty
}

// GetThirdPartyOk returns a tuple with the ThirdParty field value
// and a boolean to check if the value has been set.
func (o *AssetCount) GetThirdPartyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThirdParty, true
}

// SetThirdParty sets field value
func (o *AssetCount) SetThirdParty(v int32) {
	o.ThirdParty = v
}

// GetTotal returns the Total field value
func (o *AssetCount) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AssetCount) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AssetCount) SetTotal(v int32) {
	o.Total = v
}

func (o AssetCount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_party"] = o.FirstParty
	toSerialize["third_party"] = o.ThirdParty
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *AssetCount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_party",
		"third_party",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetCount := _AssetCount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetCount)

	if err != nil {
		return err
	}

	*o = AssetCount(varAssetCount)

	return err
}

type NullableAssetCount struct {
	value *AssetCount
	isSet bool
}

func (v NullableAssetCount) Get() *AssetCount {
	return v.value
}

func (v *NullableAssetCount) Set(val *AssetCount) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetCount) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetCount(val *AssetCount) *NullableAssetCount {
	return &NullableAssetCount{value: val, isSet: true}
}

func (v NullableAssetCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


