/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LogForwarderCreateParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogForwarderCreateParams{}

// LogForwarderCreateParams struct for LogForwarderCreateParams
type LogForwarderCreateParams struct {
	Name string `json:"name"`
}

type _LogForwarderCreateParams LogForwarderCreateParams

// NewLogForwarderCreateParams instantiates a new LogForwarderCreateParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogForwarderCreateParams(name string) *LogForwarderCreateParams {
	this := LogForwarderCreateParams{}
	this.Name = name
	return &this
}

// NewLogForwarderCreateParamsWithDefaults instantiates a new LogForwarderCreateParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogForwarderCreateParamsWithDefaults() *LogForwarderCreateParams {
	this := LogForwarderCreateParams{}
	return &this
}

// GetName returns the Name field value
func (o *LogForwarderCreateParams) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LogForwarderCreateParams) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LogForwarderCreateParams) SetName(v string) {
	o.Name = v
}

func (o LogForwarderCreateParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogForwarderCreateParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *LogForwarderCreateParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogForwarderCreateParams := _LogForwarderCreateParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogForwarderCreateParams)

	if err != nil {
		return err
	}

	*o = LogForwarderCreateParams(varLogForwarderCreateParams)

	return err
}

type NullableLogForwarderCreateParams struct {
	value *LogForwarderCreateParams
	isSet bool
}

func (v NullableLogForwarderCreateParams) Get() *LogForwarderCreateParams {
	return v.value
}

func (v *NullableLogForwarderCreateParams) Set(val *LogForwarderCreateParams) {
	v.value = val
	v.isSet = true
}

func (v NullableLogForwarderCreateParams) IsSet() bool {
	return v.isSet
}

func (v *NullableLogForwarderCreateParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogForwarderCreateParams(val *LogForwarderCreateParams) *NullableLogForwarderCreateParams {
	return &NullableLogForwarderCreateParams{value: val, isSet: true}
}

func (v NullableLogForwarderCreateParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogForwarderCreateParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


