/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedAPIEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedAPIEndpoint{}

// PaginatedAPIEndpoint struct for PaginatedAPIEndpoint
type PaginatedAPIEndpoint struct {
	Items []Endpoint `json:"items"`
	Page int32 `json:"page"`
	Pages int32 `json:"pages"`
	Size int32 `json:"size"`
	Total int32 `json:"total"`
}

type _PaginatedAPIEndpoint PaginatedAPIEndpoint

// NewPaginatedAPIEndpoint instantiates a new PaginatedAPIEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedAPIEndpoint(items []Endpoint, page int32, pages int32, size int32, total int32) *PaginatedAPIEndpoint {
	this := PaginatedAPIEndpoint{}
	this.Items = items
	this.Page = page
	this.Pages = pages
	this.Size = size
	this.Total = total
	return &this
}

// NewPaginatedAPIEndpointWithDefaults instantiates a new PaginatedAPIEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedAPIEndpointWithDefaults() *PaginatedAPIEndpoint {
	this := PaginatedAPIEndpoint{}
	return &this
}

// GetItems returns the Items field value
func (o *PaginatedAPIEndpoint) GetItems() []Endpoint {
	if o == nil {
		var ret []Endpoint
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginatedAPIEndpoint) GetItemsOk() ([]Endpoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginatedAPIEndpoint) SetItems(v []Endpoint) {
	o.Items = v
}

// GetPage returns the Page field value
func (o *PaginatedAPIEndpoint) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PaginatedAPIEndpoint) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PaginatedAPIEndpoint) SetPage(v int32) {
	o.Page = v
}

// GetPages returns the Pages field value
func (o *PaginatedAPIEndpoint) GetPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *PaginatedAPIEndpoint) GetPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pages, true
}

// SetPages sets field value
func (o *PaginatedAPIEndpoint) SetPages(v int32) {
	o.Pages = v
}

// GetSize returns the Size field value
func (o *PaginatedAPIEndpoint) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PaginatedAPIEndpoint) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PaginatedAPIEndpoint) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *PaginatedAPIEndpoint) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PaginatedAPIEndpoint) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PaginatedAPIEndpoint) SetTotal(v int32) {
	o.Total = v
}

func (o PaginatedAPIEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedAPIEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["page"] = o.Page
	toSerialize["pages"] = o.Pages
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *PaginatedAPIEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"page",
		"pages",
		"size",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedAPIEndpoint := _PaginatedAPIEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedAPIEndpoint)

	if err != nil {
		return err
	}

	*o = PaginatedAPIEndpoint(varPaginatedAPIEndpoint)

	return err
}

type NullablePaginatedAPIEndpoint struct {
	value *PaginatedAPIEndpoint
	isSet bool
}

func (v NullablePaginatedAPIEndpoint) Get() *PaginatedAPIEndpoint {
	return v.value
}

func (v *NullablePaginatedAPIEndpoint) Set(val *PaginatedAPIEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedAPIEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedAPIEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedAPIEndpoint(val *PaginatedAPIEndpoint) *NullablePaginatedAPIEndpoint {
	return &NullablePaginatedAPIEndpoint{value: val, isSet: true}
}

func (v NullablePaginatedAPIEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedAPIEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


