/*
Ghost API

The Ghost API

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointCount{}

// EndpointCount struct for EndpointCount
type EndpointCount struct {
	FirstParty int32 `json:"first_party"`
	ThirdParty int32 `json:"third_party"`
	Total int32 `json:"total"`
}

type _EndpointCount EndpointCount

// NewEndpointCount instantiates a new EndpointCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointCount(firstParty int32, thirdParty int32, total int32) *EndpointCount {
	this := EndpointCount{}
	this.FirstParty = firstParty
	this.ThirdParty = thirdParty
	this.Total = total
	return &this
}

// NewEndpointCountWithDefaults instantiates a new EndpointCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointCountWithDefaults() *EndpointCount {
	this := EndpointCount{}
	return &this
}

// GetFirstParty returns the FirstParty field value
func (o *EndpointCount) GetFirstParty() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FirstParty
}

// GetFirstPartyOk returns a tuple with the FirstParty field value
// and a boolean to check if the value has been set.
func (o *EndpointCount) GetFirstPartyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstParty, true
}

// SetFirstParty sets field value
func (o *EndpointCount) SetFirstParty(v int32) {
	o.FirstParty = v
}

// GetThirdParty returns the ThirdParty field value
func (o *EndpointCount) GetThirdParty() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ThirdParty
}

// GetThirdPartyOk returns a tuple with the ThirdParty field value
// and a boolean to check if the value has been set.
func (o *EndpointCount) GetThirdPartyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThirdParty, true
}

// SetThirdParty sets field value
func (o *EndpointCount) SetThirdParty(v int32) {
	o.ThirdParty = v
}

// GetTotal returns the Total field value
func (o *EndpointCount) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *EndpointCount) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *EndpointCount) SetTotal(v int32) {
	o.Total = v
}

func (o EndpointCount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_party"] = o.FirstParty
	toSerialize["third_party"] = o.ThirdParty
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *EndpointCount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_party",
		"third_party",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointCount := _EndpointCount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointCount)

	if err != nil {
		return err
	}

	*o = EndpointCount(varEndpointCount)

	return err
}

type NullableEndpointCount struct {
	value *EndpointCount
	isSet bool
}

func (v NullableEndpointCount) Get() *EndpointCount {
	return v.value
}

func (v *NullableEndpointCount) Set(val *EndpointCount) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointCount) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointCount(val *EndpointCount) *NullableEndpointCount {
	return &NullableEndpointCount{value: val, isSet: true}
}

func (v NullableEndpointCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


